#!/usr/bin/env bash
#
# build.sh — populate bin/lib with this app's runtime dependencies.
#
# bin/lib is a build artifact and is not tracked in git. Run this once after
# cloning, and again whenever requirements.txt changes.
#
# Usage:
#   ./build.sh                                  # install the pinned lockfile
#   ./build.sh --freeze                         # re-resolve, then rewrite the lockfile
#   SPLUNK_PYTHON=/path/to/python3 ./build.sh    # point at a specific interpreter
#
set -euo pipefail

FREEZE=0
if [[ "${1:-}" == "--freeze" ]]; then
    FREEZE=1
elif [[ $# -gt 0 ]]; then
    echo "usage: $0 [--freeze]" >&2
    exit 2
fi

APP_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
LIB_DIR="$APP_DIR/bin/lib"
VENDORED_SDK="$APP_DIR/bin/splunklib"

# ---------------------------------------------------------------------------
# Interpreter. splunklib.ai requires 3.13, matching python.required in
# commands.conf, so build against the same interpreter Splunk will use.
# ---------------------------------------------------------------------------
PY="${SPLUNK_PYTHON:-${SPLUNK_HOME:-/opt/splunk}/bin/python3}"

if [[ ! -x "$PY" ]]; then
    echo "error: interpreter not found at '$PY'." >&2
    echo "       Set SPLUNK_HOME, or SPLUNK_PYTHON to a Python 3.13+ binary." >&2
    exit 1
fi

PY_VER="$("$PY" -c 'import sys; print("%d.%d" % sys.version_info[:2])')"
if ! "$PY" -c 'import sys; sys.exit(0 if sys.version_info >= (3, 13) else 1)'; then
    echo "error: Python 3.13+ is required (found $PY_VER at $PY)." >&2
    echo "       splunklib.ai refuses to import on older versions." >&2
    exit 1
fi

echo "==> Building with $PY (Python $PY_VER)"

# ---------------------------------------------------------------------------
# Always start from an empty lib directory.
#
# Installing over an existing tree is what produced the state this script
# replaces: three different openai dist-info directories, two anyio, two
# certifi, and so on. Stale metadata makes importlib.metadata report the wrong
# version and leaves pip unable to reason about what is installed.
# ---------------------------------------------------------------------------
echo "==> Clearing $LIB_DIR"
rm -rf "$LIB_DIR"
mkdir -p "$LIB_DIR"

# ---------------------------------------------------------------------------
# Install from the lockfile by default so builds are reproducible; transitive
# versions drift noticeably between resolutions otherwise. --freeze re-resolves
# from requirements.txt and rewrites the lock.
# ---------------------------------------------------------------------------
LOCK="$APP_DIR/requirements.lock.txt"
if [[ $FREEZE -eq 0 && -f "$LOCK" ]]; then
    echo "==> Installing pinned dependencies from requirements.lock.txt"
    SOURCE_FILE="$LOCK"
else
    echo "==> Resolving dependencies from requirements.txt"
    SOURCE_FILE="$APP_DIR/requirements.txt"
fi

"$PY" -m pip install \
    --upgrade \
    --target "$LIB_DIR" \
    -r "$SOURCE_FILE"

# ---------------------------------------------------------------------------
# Vendored Splunk SDK.
#
# The build that provides splunklib.ai is not resolvable from a public index,
# so it stays in git under bin/splunklib and is copied in here. bin/lib is
# prepended to sys.path by the search commands, so this copy is the one that
# gets imported.
# ---------------------------------------------------------------------------
if [[ -d "$VENDORED_SDK" ]]; then
    echo "==> Installing vendored Splunk SDK from bin/splunklib"
    rm -rf "$LIB_DIR/splunklib"
    cp -R "$VENDORED_SDK" "$LIB_DIR/splunklib"
else
    echo "warning: $VENDORED_SDK is missing; splunklib.ai will be unavailable." >&2
fi

# ---------------------------------------------------------------------------
# Strip bytecode. It is regenerated on first import, is interpreter-specific,
# and previously accounted for 3320 of the 7233 files committed to git.
# ---------------------------------------------------------------------------
echo "==> Removing bytecode caches"
find "$LIB_DIR" -type d -name '__pycache__' -prune -exec rm -rf {} +
find "$LIB_DIR" -type f -name '*.py[co]' -delete

if [[ $FREEZE -eq 1 ]]; then
    echo "==> Rewriting requirements.lock.txt"
    {
        echo "# Generated by build.sh --freeze on $(date +%Y-%m-%d). Do not edit by hand."
        echo "# Full transitive closure, pinned for reproducible builds."
        echo "# Regenerate after changing requirements.txt."
        # The vendored SDK is not installed from an index, so it is excluded.
        ls -d "$LIB_DIR"/*.dist-info \
            | sed "s|^$LIB_DIR/||; s|\.dist-info$||" \
            | sed 's|^\(.*\)-\([0-9][^-]*\)$|\1==\2|' \
            | grep -v '^splunk' \
            | sort -f
    } > "$LOCK"
    echo "    pinned $(grep -c '==' "$LOCK") packages"
fi

echo "==> Done. $(find "$LIB_DIR" -type f | wc -l | tr -d ' ') files, $(du -sh "$LIB_DIR" | cut -f1)."
echo
echo "Note: compiled extensions (.so) in bin/lib are built for this platform."
echo "Do not copy bin/lib between machines — run ./build.sh on each one."
