# etc/apps/splunk_ai/default/agent_config.conf

[ollama]
base_url = http://localhost:11434/api/chat
model_name = llama3
api_key = none

[gemini]
base_url = https://generativelanguage.googleapis.com/v1beta/models/
model_name = gemini-3.1-flash-lite
api_key = YOURTOKENKEY