# default/app.conf

[install]
is_configured = 0
build = 1
install_source_checksum = 2a3425884b63ced466ac8bee83f3c705b1f1d303

[ui]
is_visible = 1
label = Splunk AI Toolkit Showcase

[launcher]
author = Xu Zou
description = A showcase app for Splunk AI capabilities including MCP Agent and RAG.
version = 1.0.3

[id]
name = splunk_ai
version = 1.0.3
