[airag]
filename = llm_rag.py
chunked = true
python.version = python3
passauth = true

[mcpagent]
chunked = true
filename = mcp_agent.py
python.version = python3
passauth = true

[llmchat]
chunked = true
filename = llmchat.py
python.version = python3
passauth = true