[airag-command]
syntax = [ | airag prompt="What is Splunk?"  provider=ollama model="llama3:lastest"]
shortdesc = [Query RAG with LLM]
usage = public

[llmchat-command]
syntax = [ | llmchat session="xxx" prompt="analyze the logs"]
shortdesc = [Chat log with LLM]
usage = public

